#!/bin/sh
sysresources=/etc/X11/xinit/.Xresources
sysxinitrcdir=/etc/X11/xinit/xinitrc.d
userresourcesdir=${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources.d
userxinitrcdir=${XDG_CONFIG_HOME:-$HOME/.config}/X11/xinit/xinitrc.d

[ -r "$sysresources" ] && xrdb -merge "$sysresources"

if [ -d "$userresourcesdir" ]; then
	for resources in "$userresourcesdir"/?*.Xresources; do
		[ -r "$resources" ] && xrdb -merge "$resources"
	done
fi

for dir in "$sysxinitrcdir" "$userxinitrcdir"; do
	if [ -d "$dir" ]; then
		for xinitrc in "$dir"/?*.sh; do
			# shellcheck source=/dev/null
			[ -r "$xinitrc" ] && . "$xinitrc"
		done
	fi
done

XDG_SESSION_TYPE=x11 exec tdm --xstart
