#!/bin/bash
export TODO_DIR=${XDG_DATA_HOME:-$HOME/.local/share}/todo

export TODO_FILE=$TODO_DIR/todo.txt
export DONE_FILE=$TODO_DIR/done.txt
export REPORT_FILE=$TODO_DIR/report.txt

export TODO_ACTIONS_DIR=${XDG_DATA_HOME:-$HOME/.local/share}/todo/actions.d

export COLOR_PROJECT=$RED
export COLOR_CONTEXT=$PURPLE
