#!/bin/sh
[ -r /etc/X11/Xresources ] && xrdb -merge /etc/X11/Xresources

xresourcesdir=${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources.d

if [ -d "$xresourcesdir" ] ; then
	for resource in "$xresourcesdir"/?*.Xresources ; do
		[ -r "$resource" ] && xrdb -merge -Dbackground_opacity=95 "$resource"
	done
	unset resource
fi

unset xresourcesdir

xinitrcdir=${XDG_CONFIG_HOME:-$HOME/.config}/X11/xinit/xinitrc.d

for dir in /etc/X11/xinit/xinitrc.d $xinitrcdir ; do
	if [ -d "$dir" ] ; then
		for xinitrc in "$dir"/?*.sh ; do
			# shellcheck source=/dev/null
			[ -x "$xinitrc" ] && . "$xinitrc"
		done
		unset xinitrc
	fi
done

unset dir xinitrcdir

exec tdm --xstart
